### ISSUE TITLE
`unsign` return type

### ISSUE THREAD

**Issue by cusxio** [AlvinTheDeveloper/cookie-signature-edge#2]
https://github.com/AlvinTheDeveloper/cookie-signature-edge/blob/da70e91a7b20531abbc31f4410fea68b0f338047/index.ts#L47

Then return type for `unsign` should be `Promise<string|false>`, since it's not possible for it to be `true`.

**Comment by AlvinTheDeveloper** [comment]
Thanks for creating this issue.
I have updated it in a7222b0

**Comment by cusxio** [comment]
Heads up, I think you have a bad publish, see

https://unpkg.com/browse/cookie-signature-edge@1.0.6/dist/index.d.ts

The types in the `dist` folder are not updated.

**Comment by AlvinTheDeveloper** [comment]
You're right. Sorry for that. I have updated the dist/ republished the whole thing.
